# Generated by Django 3.2.3 on 2021-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_via',
            field=models.CharField(choices=[('CASH', 'Cash On Delivery'), ('E-SEWA', 'E-sewa'), ('KHALTI', 'Khalti')], max_length=150),
        ),
    ]
